spring:
  application:
    name: challenger-be
  datasource:
    url: jdbc:mysql://localhost:3306/challenger_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
